# Edit this file to add configuration that is specific to your instance
# Find additional documentation at https://docs.docker.com/compose/extends/

x-variables:
    - &shared-volumes
        volumes:
            # These mounts are specific to Fred Hutch:

            # SSSD / nscd sockets for authentication against Active Directory via PAM
            # (only on hosts running sssd / nscd, otherwise docker creates empty directories)
            - /var/run/nscd/socket:/var/run/nscd/socket
            - /var/lib/sss/pipes:/var/lib/sss/pipes
            - /var/lib/sss/mc:/var/lib/sss/mc:ro

            - /home:/home:shared
            - /efs/:/efs/
            - /fh/economy:/fh/economy:shared
            - /fh/fast:/fh/fast:shared
            - /fh/secure:/fh/secure:shared
            - /fh/silver:/fh/silver:shared
            - /shared:/shared:shared
            - /hpc/temp:/hpc/temp:shared
            - /fh/working:/fh/working:shared

services:
    app:
        <<: *shared-volumes
    celery:
        <<: *shared-volumes

