# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Only allow password connections from this host; the containers use host networking
host    all             all             samehost                scram-sha-256
